### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 10.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/GrahamCampbell/Laravel-Manager/pull/18/commits/941d8e071ec7264a8d20c290126d72faa33cfc29?w=1) for Laravel 10. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/Laravel-Manager.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "graham-campbell/manager": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by svpernova09** [comment]
Might be some issues w/ this


composer.json require:

```
    "require": {
        "php": "^8.1, <8.2",
        "doctrine/dbal": "^3.1",
        "graham-campbell/github": "dev-l10-compatibility",
        "graham-campbell/manager": "dev-l10-compatibility",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^10.0",
        "laravel/socialite": "^5.2",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^4.0",
        "marvinlabs/laravel-discord-logger": "dev-l10-compatibility",
        "php-http/guzzle7-adapter": "^0.1.1",
        "spatie/laravel-sluggable": "^3.3",
        "svpernova09/lavishsoftprovider": "0.3.0"
    },
```

composer.json repositories:

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/Laravel-GitHub.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-discord-logger.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/Laravel-Manager.git"
        }
    ]
```

┌─(~/Code/joemultiboxer)(master M:1 S:1)
└─(2)─ composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires graham-campbell/github dev-l10-compatibility -> satisfiable by graham-campbell/github[dev-l10-compatibility].
    - graham-campbell/github dev-l10-compatibility requires graham-campbell/manager ^4.7 -> found graham-campbell/manager[v4.7.0, 4.7.x-dev] but it conflicts with your root composer.json require (dev-l10-compatibility).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

┌─(~/Code/joemultiboxer)(master M:1 S:1)
└─(2)─ composer update -W
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires graham-campbell/github dev-l10-compatibility -> satisfiable by graham-campbell/github[dev-l10-compatibility].
    - graham-campbell/github dev-l10-compatibility requires graham-campbell/manager ^4.7 -> found graham-campbell/manager[v4.7.0, 4.7.x-dev] but it conflicts with your root composer.json require (dev-l10-compatibility).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

**Comment by RohanSakhale** [comment]
@GrahamCampbell any chance you can take a look at this?

**Comment by Tofandel** [comment]
@svpernova09 Your issue is that graham-campbell/github requires graham-campbell/manager and both of them have a dependency on laravel 9 but you're just using PR's meant to add support to laravel 10, and by using those vcs there is a version mismatch because the dev-l10-compatibility branch version is not resolved as version 4.7 and thus doesn't resolve to a set of valid dependencies

Those PR's are not meant to crossreference each other or they would loose their purpose, for this too work you'd need to fork the github-l10-compatibility yourself and change the dependency like you did

```
"graham-campbell/manager": "dev-l10-compatibility",
```

Or just wait a bit until we get a new version

**Comment by svpernova09** [comment]
> @svpernova09 Your issue is that graham-campbell/github requires graham-campbell/manager and both of them have a dependency on laravel 9 but you're just using PR's meant to add support to laravel 10, and by using those vcs there is a version mismatch because the dev-l10-compatibility branch version is not resolved as version 4.7 and thus doesn't resolve to a set of valid dependencies
> 
> Those PR's are not meant to crossreference each other or they would loose their purpose, for this too work you'd need to fork the github-l10-compatibility yourself and change the repository and dependency like you did
> 
> ```
> "graham-campbell/manager": "dev-l10-compatibility",
>  "repositories": [
>         {
>             "type": "vcs",
>             "url": "https://github.com/laravel-shift/Laravel-Manager.git"
>         }
>     ]
> ```
> 
> Or just wait a bit until we get a new version

Cheers for the reply! And appreciate your work. Thanks.

**Comment by Tofandel** [comment]
@svpernova09 I found a much better and correct way to get this to work correctly

In your composer.json just alias the laravel shift version as a compatible version, no need to fork anything
```
"graham-campbell/github": "dev-l10-compatibility as 11.0.x-dev",
"graham-campbell/manager": "dev-l10-compatibility as 4.7.x-dev",
```

**Comment by GrahamCampbell** [comment]
I will look at Laravel 10 compatibility, when I get some time. [Sponsoring me](https://github.com/sponsors/GrahamCampbell) can help me make time. I am spread thin across many open source projects including Guzzle. This PR is not mergable in its current state, so I'm going to close it out, and move this to an issue: https://github.com/GrahamCampbell/Laravel-Manager/issues/19. ;)

**Comment by GrahamCampbell** [comment]
[v5.0.0](https://github.com/GrahamCampbell/Laravel-Manager/releases/tag/v5.0.0) has been released. 🎉

It has been 5 years since the last breaking change here ([v4.0.0](https://github.com/GrahamCampbell/Laravel-Manager/releases/tag/v4.0.0) was released in February 2018), and I'm aware that this package is widely depended upon (which was the reason I have held off on making and breaking changes for so long), although it was inevitable that I was going to drop some older PHP and Laravel versions at some point, and add some return types to the interfaces and classes in this package. I've decided that now is the right time to do that. The new version of this package has property and return types, and supports the following versions:

* PHP 7.4, 8.0, 8.1, and 8.2
* Laravel 8, 9, and 10

My decision to go with PHP 7.4 and Laravel 8 as minimum versions are based on laravel/framework [installation metrics](https://packagist.org/packages/laravel/framework/stats) from January 2023, both showing installations by Laravel version and PHP version, and the fact that PHP 7.4 supports [property types](https://wiki.php.net/rfc/typed_properties_v2) and [covariant return types](https://wiki.php.net/rfc/covariant-returns-and-contravariant-parameters).

**Pull request closed without merging**
