### PR TITLE
Add Laravel 5.6 Support

### PR DESCRIPTION
**Pull request by irazasyed**

### CODE REVIEW

**Comment by cjmartino** [comment]
Please merge! :-)

**Comment by GrahamCampbell** [comment]
In 2 weeks, I am upgrading all of my packages to only support 5.5 and 5.6 and PHP 7.1.3+. In the meanwhile I will not be accepting any PRs.

**Comment by johannesschobel** [comment]
in 2 weeks? seems kind of long time till then..

**Comment by GrahamCampbell** [comment]
I'm not being funny, but what's the big rush to upgrade? Laravel 5.5 LTS is a solid release.

Here is the number of laravel/framework downloads from January:

image

Why is it that just because the 5.6 happens to have a tag, that everything must be upgraded instantly? By comparison, Laravel 4.1 got more downloads than 5.6 in January!

**Comment by johannesschobel** [comment]
Hey man, i really appreciate your hard-work (on your own packages as well as on laravel itself). I know, that L5.5 is a stable (and LTS) release - which is quite appealing for other developers..

However, I am pretty sure that some other would like to try out L5.6 (for whatever reason) and may want to update their application, but cannot because of dependencies.. That beeing said, take your time for updating your packages, testing your code and so on. It is better to have a stable set of packages than "rushing" to another version..

Keep your good work up, i really appreciate it! I didn't meant to sound harsh on this one.. 

Cheers

BTW: the downloads are pretty impressive - holy shit..

**Comment by GrahamCampbell** [comment]
Actually, I'm going to upgrade this package today. I can see a lot of other packages depend on it, and this one is pretty easy to upgrade.

**Comment by laurencei** [comment]
thanks @GrahamCampbell

**Pull request closed without merging**
