### PR TITLE
Bump branch alias

### PR DESCRIPTION
**Pull request by vinkla**
Updated the branch alias to 2.5.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Will do it on all the packages later. :)

**Comment by GrahamCampbell** [comment]
Probably shouldn't have closed this, lol. I'll cherry-pick your commit.

**Comment by vinkla** [comment]
No worries, I just wanted to stress you :smirk:

**Comment by GrahamCampbell** [comment]
I "git am"ed it already. :)

**Comment by GrahamCampbell** [comment]
Same as git apply, only it commits as the original author too.

**Comment by vinkla** [comment]
Oh, didn't know that.

**Comment by GrahamCampbell** [comment]
Me neither until just now. Had to Google for it. I knew it existed (since I've used that functionality through a GUI before), but never knew what it was called until now.

🎄

**Pull request closed without merging**
